"""empty message

Revision ID: e5d42be9a1ff
Revises: None
Create Date: 2016-08-21 05:20:12.441329

"""

# revision identifiers, used by Alembic.
revision = 'e5d42be9a1ff'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moulds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mould_name', sa.String(length=64), nullable=True),
    sa.Column('mould_code', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mould_id', sa.Integer(), nullable=True),
    sa.Column('parts_name', sa.String(length=64), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('parts_length', sa.Integer(), nullable=True),
    sa.Column('parts_width', sa.Integer(), nullable=True),
    sa.Column('parts_height', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['mould_id'], ['moulds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.Column('process_name', sa.String(length=64), nullable=True),
    sa.Column('process_content', sa.String(length=64), nullable=True),
    sa.Column('working_hours', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('process_resources', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processes')
    op.drop_table('parts')
    op.drop_table('moulds')
    op.drop_table('materials')
    ### end Alembic commands ###
