estimate:
  # restart: always
  build: ./app
  # image: gevin/octblog:0.2.4.2
  ports:
    - "8000:8000"
    - "5000:5000"
  #links:
  #  - mysql:mysql
  volumes:
    - ./app:/usr/src/app
  env_file: .env


